### ISSUE TITLE
Any tutorial?

### ISSUE THREAD

**Issue by cyantarek** [eko/gofast#1]
Hello we will greatly appreciate if you can make a tutorial on how you made it. Thanks a lot

**Comment by eko** [comment]
Hello,

Thank you for your interest into a tutorial: this project has been written during in the time in order to help me learning Go language.

I've added functionalities one by one (request/response, templating, CORS support, middlewares, ...) as I needed them.

I will be happy to exchange with you if you have any question but I will not write any tutorial as the README documentation is already a good place with examples of all components.

Thank you
